### ISSUE TITLE
feature request - implement link embed

### ISSUE THREAD

**Issue by KroniiHatesYou** [OnlyKronii/OnlyKronii.github.io#3]
like in https://faunaraara.com/

![image](https://user-images.githubusercontent.com/104419920/165278263-5a70112b-2805-4b24-b5ed-62983ab1fb9e.png)

**Comment by OnlyKronii** [comment]
Fixed it!
Thank you for pointing it out

**Comment by OnlyKronii** [comment]
![image](https://user-images.githubusercontent.com/104379559/165444930-30911410-2513-4ea8-8bea-4edfda0c0a01.png)

**Comment by OnlyKronii** [comment]
Before close it, I gonna add more detail

**Comment by OnlyKronii** [comment]
![image](https://user-images.githubusercontent.com/104379559/166167887-8f022188-a438-4ed9-9a13-6f0f0e93f9c2.png)
